---
name: Feature Request
description: Request a new feature
title: 'feature request: '

body:
  - type: markdown
    attributes:
      value: |
        By submitting this issue you agree to this project's Code of Conduct!

  - type: checkboxes
    id: initial-checks
    attributes:
      label: Initial checks
      description: Please read these carefully.
      options:
        - label: I checked that the feature is now already implemented.
          required: true

  - type: textarea
    id: question
    attributes:
      label: State your request
      render: Markdown
    validations:
      required: true
