---
name: Question
description: Ask a question
title: 'question: '

body:
  - type: markdown
    attributes:
      value: |
        By submitting this issue you agree to this project's Code of Conduct!

  - type: textarea
    id: question
    attributes:
      label: State your question
      placeholder: Is P = NP?
      render: Markdown
    validations:
      required: true
