name: Lint

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read

env:
  IMAGE_TAG: '2.7.0'

jobs:
  EditorConfig:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run the Linter
        run: |
          docker run --rm --tty --volume "${GITHUB_WORKSPACE}:/ci:ro" --workdir '/ci' \
            mstruebing/editorconfig-checker:${IMAGE_TAG} ec -config "/ci/.editorconfig"
