name: Linting

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  IMAGE_TAG_EC: '2.7.0'

jobs:
  EditorConfig:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run the Linter
        run: |
          docker run --rm --volume "${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE}:ro" --workdir "${GITHUB_WORKSPACE}" \
            "docker.io/mstruebing/editorconfig-checker:${IMAGE_TAG_EC}" \
            ec -disable-max-line-length -exclude '^.git'
